name: Build and Push Docker Image

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Extract SHA, Branch and Tag
        id: vars
        run: |
          echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}
          echo ::set-output name=short_sha::${GITHUB_SHA::7}
      - name: Git Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU (Docker build preparation)
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx (Docker build preparation)
        uses: docker/setup-buildx-action@v1
      - name: Say Hello
        run: echo "Hello!"